name: linear_gradient
description: Linear gradient with 300+ different color combination. Also, it will options for change gradient orientation Vertical and Horizontal.
version: 0.1.12
author: Techno Prashant <prashant09mca@gmail.com>
homepage: https://github.com/Prashant09mca/flutter_linear_gradient

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
